export const COUNTRIES = [
  { value: 'VN', label: 'Việt Nam' },
  { value: 'CN', label: 'Trung Quốc' },
  { value: 'TW', label: 'Đài Loan' },
  { value: 'JP', label: 'Nhật Bản' },
  { value: 'KR', label: 'Hàn Quốc' },
  { value: 'SG', label: 'Singapore' },
  { value: 'TH', label: 'Thái Lan' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'US', label: 'Mỹ' },
  { value: 'DE', label: 'Đức' },
  { value: 'GB', label: 'Anh' },
  { value: 'FR', label: 'Pháp' },
  { value: 'NL', label: 'Hà Lan' },
  { value: 'SE', label: 'Thụy Điển' },
  { value: 'AU', label: 'Úc' },
  { value: 'IN', label: 'Ấn Độ' },
  { value: 'HK', label: 'Hồng Kông' },
]
